CREATE TABLE IF NOT EXISTS events_v1
(
	generator String,
	timestamp DateTime,
	name String,
	actorId String,
	actorType String,
	env String,
	eventId String,
	event String,
	subEvent String,
	timeTaken UInt32,
	os String,
	browser String,
	browserVersion String,
	deviceType String,
	platform String,
	ip String,
	botId UUID,
	userId UUID,
	orgId UUID,
	conversationId UUID,
	messageId UUID,
	audiourl String,
	audioId UUID,
	text String,
	mediaIds String,
	spellCorrectedText String,
	error String,
	timeElapsed UInt32,
	spellCheckTimeTaken UInt32,
	phoneNumber String,
	createdAt DateTime,
	queryId UUID,
	deviceId String,
	userManagementUrl String,
	textInEnglish String,
	userHistory String,
	coreferencedText String,
	block String,
	district String,
	queryClass String,
	NER String,
	similarChunks String,
	responseInEnglish String,
	response String,
	feedback String,
	reaction UInt32,
	timesAudioUsed UInt32
)
ENGINE = MergeTree
ORDER BY timestamp;
