receivers:
  otlp:
    protocols:
      grpc:
        endpoint: '0.0.0.0:4318'
      http:
        endpoint: '0.0.0.0:4317'

processors:
  batch:
    send_batch_size: 1024
    timeout: 5s

exporters:
  zipkin:
    endpoint: 'http://zipkin:9411/api/v2/spans'
  otlp/jaeger:
    endpoint: jaeger-all-in-one:4317
    tls:
      insecure: true

  logging:
    loglevel: debug
    # sampling_initial: 1
    # sampling_thereafter: 1

extensions:
  health_check:
    endpoint: localhost:13133

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, zipkin, otlp/jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
